name: commoncents
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_fonts: ^2.1.0
  shared_preferences: ^2.1.2
  flutter_native_splash: ^2.2.11
  animated_bottom_navigation_bar: ^1.2.0
  anim_search_bar: ^2.0.3

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  
  assets:
  - assets/logo.png
