name: commoncents
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_fonts: ^2.1.0
  shared_preferences: ^2.1.2
  flutter_native_splash: ^2.2.11
  animated_bottom_navigation_bar: ^1.2.0
  anim_search_bar: ^2.0.3
  toggle_switch: ^2.1.0
  numberpicker: ^2.1.2
  iconsax: ^0.0.8
  webkul_textfield_with_label: ^0.0.4
  kumi_popup_window: ^2.0.1
  passwordfield: ^0.2.0
  flutter_switch: ^0.3.2
  flutter_animated_button: ^2.0.3
  candlesticks: ^2.1.0
  http: ^0.13.6
  syncfusion_flutter_charts: ^22.1.34
  web_socket_channel: ^2.4.0
  url_launcher: ^6.1.11
  syncfusion_flutter_gauges: ^22.1.34
  fl_chart: ^0.62.0
  intl: ^0.18.1

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  
  assets:
  - assets/logo.png
