// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBanb-RpzdBmT1K0ldfTbberdxFzbUj824',
    appId: '1:860551647147:web:8d8683f8a4d543e5718cee',
    messagingSenderId: '860551647147',
    projectId: 'drc-project-99da9',
    authDomain: 'drc-project-99da9.firebaseapp.com',
    storageBucket: 'drc-project-99da9.appspot.com',
    measurementId: 'G-D8WZX9D7H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAazSEKlllGbElUFPUrsdvpwjf93CMahPA',
    appId: '1:860551647147:android:1f1df83dec479088718cee',
    messagingSenderId: '860551647147',
    projectId: 'drc-project-99da9',
    storageBucket: 'drc-project-99da9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Sozbsc8hHSEAD9TA8zS1ktTuFQ99FKU',
    appId: '1:860551647147:ios:d1af2f279a7b18fd718cee',
    messagingSenderId: '860551647147',
    projectId: 'drc-project-99da9',
    storageBucket: 'drc-project-99da9.appspot.com',
    androidClientId: '860551647147-85p0u9gbchd2lnjp3mfdg2okif7q1rqd.apps.googleusercontent.com',
    iosClientId: '860551647147-hshrp9q3c46ndh0so08ma1ran0pftgmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.commoncents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Sozbsc8hHSEAD9TA8zS1ktTuFQ99FKU',
    appId: '1:860551647147:ios:d1af2f279a7b18fd718cee',
    messagingSenderId: '860551647147',
    projectId: 'drc-project-99da9',
    storageBucket: 'drc-project-99da9.appspot.com',
    androidClientId: '860551647147-85p0u9gbchd2lnjp3mfdg2okif7q1rqd.apps.googleusercontent.com',
    iosClientId: '860551647147-hshrp9q3c46ndh0so08ma1ran0pftgmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.commoncents',
  );
}
