// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZWaGK24RNEFrp8ZqjihHuVwCIQZuq9vc',
    appId: '1:402359730833:web:d6bf41b7998ff86168f530',
    messagingSenderId: '402359730833',
    projectId: 'commoncents-7b521',
    authDomain: 'commoncents-7b521.firebaseapp.com',
    storageBucket: 'commoncents-7b521.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-KSqF7HFuvqApCYi5a-ZNXx0Vfu2es4Y',
    appId: '1:402359730833:android:184aeaba3a7df78668f530',
    messagingSenderId: '402359730833',
    projectId: 'commoncents-7b521',
    storageBucket: 'commoncents-7b521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAchxouvB27dZVc7tDkrlJl-u8Gvtjl1J4',
    appId: '1:402359730833:ios:ace17503069c54ca68f530',
    messagingSenderId: '402359730833',
    projectId: 'commoncents-7b521',
    storageBucket: 'commoncents-7b521.appspot.com',
    iosClientId: '402359730833-ca340bhra5lhrn2a19i64j51ebucrjpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.commoncents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAchxouvB27dZVc7tDkrlJl-u8Gvtjl1J4',
    appId: '1:402359730833:ios:ace17503069c54ca68f530',
    messagingSenderId: '402359730833',
    projectId: 'commoncents-7b521',
    storageBucket: 'commoncents-7b521.appspot.com',
    iosClientId: '402359730833-ca340bhra5lhrn2a19i64j51ebucrjpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.commoncents',
  );
}
