// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxHAJJaGjbtCrp7dgRSOLadOhHSaE3XZ8',
    appId: '1:671959239574:web:449366c1f7681ccf6e2bb7',
    messagingSenderId: '671959239574',
    projectId: 'commoncents2-56999',
    authDomain: 'commoncents2-56999.firebaseapp.com',
    storageBucket: 'commoncents2-56999.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY-_ONgmmPzcq3f2jJ9xxutlRvn0j5c7s',
    appId: '1:671959239574:android:a08cd286d20f9b606e2bb7',
    messagingSenderId: '671959239574',
    projectId: 'commoncents2-56999',
    storageBucket: 'commoncents2-56999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsBRg7j-smm94GvYf1FvPhNJyeT6KM62A',
    appId: '1:671959239574:ios:fd59090bcd2c23a56e2bb7',
    messagingSenderId: '671959239574',
    projectId: 'commoncents2-56999',
    storageBucket: 'commoncents2-56999.appspot.com',
    iosClientId: '671959239574-5lvmmic960t9un315vm4mgk95d4qtqso.apps.googleusercontent.com',
    iosBundleId: 'com.example.commoncents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsBRg7j-smm94GvYf1FvPhNJyeT6KM62A',
    appId: '1:671959239574:ios:fd59090bcd2c23a56e2bb7',
    messagingSenderId: '671959239574',
    projectId: 'commoncents2-56999',
    storageBucket: 'commoncents2-56999.appspot.com',
    iosClientId: '671959239574-5lvmmic960t9un315vm4mgk95d4qtqso.apps.googleusercontent.com',
    iosBundleId: 'com.example.commoncents',
  );
}
